
export const SEND_SMHI_REQUESTCURRENT = "SEND_SMHI_REQUESTCURRENT"
export const SUCCESS_SMHI_REQUESTCURRENT= "SUCCESS_SMHI_REQUESTCURRENT"
export const FAILD_SMHI_REQUESTCURRENT = "FAILD_SMHI_REQUESTCURRENT"
export const SEND_SMHI_REQUEST_LASTYEAR = "SEND_SMHI_REQUEST_LASTYEAR"
export const SUCCESS_SMHI_REQUESTLASTYEAR = "SUCCESS_SMHI_REQUESTLASTYEAR"
export const FAILD_SMHI_REQUESTLASTYEAR = "FAILD_SMHI_REQUESTLASTYEAR"


